name: Auto Post _3 (段落直接發)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run post_3
        env:
          THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_API_KEY }}
          NOTION_TOKEN_2: ${{ secrets.NOTION_TOKEN_2 }}
          NOTION_DATABASE_ID_3: ${{ secrets.NOTION_DATABASE_ID_3 }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python post_3.py
